# Name of the GitHub Actions workflow
name: ML Model Training Pipeline
# Define the triggers for this workflow
on:
  push:                      # Run workflow on "push" events
    branches: [ "main" ]     # Only when code is pushed to the "main" branch
 # Define the set of jobs to run
jobs:
  build:                    # Job name (you can rename it if needed)
    runs-on: ubuntu-latest   # The VM environment to run this job (Ubuntu Linux)
      steps:                   # Ordered list of steps inside the job
            # Step 1: Checkout the repository code so it's available in the VM
            - name: Checkout repository
              uses: actions/checkout@v4
      
            # Step 2: Set up a Python environment
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"   # Specify Python version
            # Step 3: Install dependencies from requirements.txt
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip   # Upgrade pip to latest version
                pip install -r requirements.txt       # Install project dependencies
             # Step 4: Run the ML training script
      - name: Run training script
        run: python train.py

            # Step 5: Upload the trained model as an artifact (for download later)
            - name: Upload model artifact
              uses: actions/upload-artifact@v4
              with:
                name: trained-model    # Artifact name in GitHub Actions UI
                path: model.pkl        # File to upload (output of training)

